const translations = {
  pt: {
    // Menu e navegação
    "grupo-unione": "grupo unione",
    "areas-negocios": "áreas de negócios",
    "investidores": "investidores",
    "polis": "polis",
    "contatos": "contactos",
    "contacte-nos": "Contacte-nos",
    "siga-nos": "Siga-nos",
    // Hero/Grupo
    "o-grupo-unione": "O Grupo Unione",
    "excelencia-angolana": "Excelência Angolana em Cada Investimento.",
    "descricao-grupo": "O Grupo Unione é um grupo empresarial e de investimento Angolano, com atuação estratégica em diversos setores-chave da economia.",
    "descricao-grupo2": "A nossa diversificação e capacidade operacional são evidenciadas por projetos de grande impacto, o que nos torna um parceiro de referência em diversas áreas de negócio, entre as quais:",
    "anos": "Anos",
    "areas-negocios-contador": "Áreas de Negócios",
    "trabalhadores": "trabalhadores",
    "clientes": "Clientes",
    // Áreas de Negócios
    "empresas": "Áreas de Negócios",
    "descricao-areas1": "A força do Grupo Unione está na sua capacidade de operar de forma integrada, articulando diferentes empresas em setores estratégicos da economia.",
    "descricao-areas2": "Esta sinergia permite executar projetos com agilidade, otimizar recursos e ampliar o impacto de cada investimento — do planeamento à entrega.",
    "descricao-areas3": "Com uma estrutura conectada que vai da produção ao serviço, da formação técnica à energia e distribuição, oferecemos soluções completas para desafios reais, criando valor sustentável nos mercados onde atuamos",
    "descricao-areas4": "Conheça a nossa estrutura integrada e veja como transformamos competências diversas em resultados concretos.",
    // Investidores
    "investidores-titulo": "Investidores",
    "descricao-investidores": "Atuamos como facilitadores estratégicos para empresas e investidores que desejam estabelecer-se em Angola, conectando oportunidades locais a capitais globais e disponibilizando suporte estruturado para investimentos sustentáveis e de longo prazo.",
    "como-apoiamos": "Como apoiamos investidores?",
    "seguranca-juridica": "Segurança jurídica e apoio à instalação",
    "oportunidade-valorizacao": "Oportunidade de valorização",
    "localizacao-estrategica": "Localização e conectividade estratégico",
    "infraestrutura-pronta": "Infraestrutura pronta para opera",
    "beneficio1": "Elaboração de projetos de arquitetura e engenharia personalizados",
    "beneficio2": "Segurança jurídica com lotes registados e transmissão automática de propriedade",
    "beneficio3": "Incubação de empresas nos primeiros anos de atividade",
    "beneficio4": "Formação de Técnicos Profissionais",
    "beneficio5": "Apoio na instalação e operação de unidades produtivas com agilidade e eficiência",
    // POLIS
    "polis-titulo": "POLIS - Polo de Desenvolvimento Integrado e Sustentabilidade",
    "descricao-polis1": "O POLIS é um projeto de referência no mercado angolano, desenvolvido e gerido pelo Grupo Unione e concebido como um Polo de Desenvolvimento Integrado e Sustentável, com infraestrutura pronta, gestão organizada e vocação para receber indústrias, empresas de serviços e projetos habitacionais de alto valor agregado.",
    "descricao-polis2": "Mais do que um empreendimento imobiliário, o POLIS oferece um ambiente estruturado, estratégico e juridicamente seguro para instalação de negócios, expansão logística e desenvolvimento habitacional com qualidade de vida.",
    "area-bruta": "Área Bruta",
    "area-construida": "Área Construída",
    "lotes": "Lotes",
    "industriais-comerciais-residenciais": "Industriais, Comerciais e Residenciais",
    "centros-desenvolvimento": "Centros de Desenvolvimento - CT",
    "cd1": "CD 1 | Industrial",
    "cd2": "CD 2 | Comércio e Serviços",
    "cd3": "CD 3 | Saúde e Estética",
    "cd4": "CD 4 | Educação e Formação",
    "cd5": "CD 5 | Hotelaria e Turismo",
    "cd6": "CD 6 | Cultura, Desporto e Lazer",
    "cd7": "CD 7 | Residencial",
    "cd8": "CD 8 | Serviços de apoio à Comunidade",
    "beneficios-investidores": "Benefícios aos Investidores",
    "beneficio-logistica": "Redução de custos logísticos e tempo de resposta",
    "beneficio-valorizacao": "Potencial de Valorização contínua com um projeto inovador e em crescimento",
    "beneficio-mercados": "Acesso simultâneo a mercados locais, nacionais e transfronteiriços",
    "beneficio-competitiva": "Vantagem competitiva na comercialização regional, especialmente na cadeia agroalimentar",
    "beneficio-importacao": "Facilidade de importação/exportação de insumos e produtos acabados",
    "saber-mais-lotes": "saber mais sobre Lotes",
    "polis-destino-estrategico": "O que torna o POLIS um destino estratégico para investidores:",
    "polis-lotes-infra": "Lotes totalmente Infraestruturados",
    "polis-suporte-desenvolvimento": "Acompanhamento e Suporte ao Desenvolvimento Empresarial",
    "polis-promocao-escoamento": "Promoção e Escoamento dos Produtos e Serviços",
    "polis-planeamento-sustentavel": "Planeamento sustentável",
    // Localização Estratégica
    "localizacao-estrategica-titulo": "Localização Estratégica",
    "descricao-localizacao1": "Com presença consolidada numa região-chave de Angola, o Grupo Unione beneficia de uma localização geográfica que impulsiona a sua capacidade logística, operacional e comercial. A proximidade com mercados relevantes, corredores logísticos e fronteiras estratégicas assegura maior eficiência nas operações e menor custo de distribuição.",
    "descricao-localizacao2": "O POLIS – Polo de Desenvolvimento Integrado e Sustentável, situado na região da Huíla, em Humpata, constitui o centro logístico e territorial das nossas operações, com acesso direto a:",
    "descricao-localizacao3": "Esta posição estratégica reforça a nossa competitividade nos mercados nacional e internacional, reduzindo tempos logísticos, aumentando a cobertura de distribuição e viabilizando operações em escala para diferentes setores.",
    // Contato
    "fale-conosco": "Fale conosco",
    "seu-nome": "Seu Nome",
    "seu-email": "Seu E-mail",
    "particular": "Particular",
    "empresa": "Empresa",
    "mensagem": "Mensagem",
    "enviar": "Enviar",
    // Footer
    "direitos-reservados": "Todos os direitos reservados",
    // Benefícios dinâmicos do POLIS - Aba 1
    "polis1_beneficio1": "Redes de saneamento.",
    "polis1_beneficio2": "Energia Elétrica.",
    "polis1_beneficio3": "Abastecimento de Água.",
    "polis1_beneficio4": "Recolha de resíduos.",
    "polis1_beneficio5": "Internet.",
    "polis1_beneficio6": "Fibra Ótica.",
    "polis1_beneficio7": "Vias Internas.",
    "polis1_beneficio8": "Segurança Privada 24h.",
    // Aba 2
    "polis2_beneficio1": "Elaboração de projetos de arquitetura e engenharia personalizados.",
    "polis2_beneficio2": "Segurança jurídica com lotes registados e transmissão automática de propriedade.",
    "polis2_beneficio3": "Incubação de empresas nos primeiros anos de atividade.",
    "polis2_beneficio4": "Formação de Técnicos Profissionais.",
    "polis2_beneficio5": "Apoio na instalação e operação de unidades produtivas com agilidade e eficiência.",
    // Aba 3
    "polis3_beneficio1": "Centro de Exposição Permanente para divulgação e comercialização de produtos e serviços das empresas instaladas.",
    "polis3_beneficio2": "Centro de Distribuição Logístico.",
    // Aba 4
    "polis4_beneficio1": "Espaços verdes e soluções de mobilidade interna.",
    "polis4_beneficio2": "Qualidade de vida no ambiente de trabalho.",
    "polis4_beneficio3": "Valorização contínua com um projeto inovador e em crescimento.",
    // Títulos dos cards do swiper
    "saude": "Saúde",
    "hotelaria": "Hotelaria",
    "energia": "Energia",
    "ensino": "Ensino",
    "agro-industria": "Agro-indústria",
    "mecanica-industrial": "Mecânica Industrial",
    "investimento-consultoria": "Investimento e Consultoria",
    "metalurgia": "Metalurgia e Metalo-mecânica",
    "tecnologia": "Telecomunicações",
    "marcenaria-carpintaria": "Marcenaria e Carpintaria",
    "construcao-civil": "construção Civil",
    "consultoria-juridica": "Consultoria jurídica"
  },
  en: {
    // Menu and navigation
    "grupo-unione": "Unione Group",
    "areas-negocios": "Business Areas",
    "investidores": "Investors",
    "polis": "polis",
    "contatos": "Contacts",
    "contacte-nos": "Contact us",
    "siga-nos": "Follow us",
    // Hero/Group
    "o-grupo-unione": "The Unione Group",
    "excelencia-angolana": "Angolan Excellence in Every Investment.",
    "descricao-grupo": "Unione Group is an Angolan business and investment group, strategically operating in key sectors of the economy.",
    "descricao-grupo2": "Our diversification and operational capacity are evidenced by high-impact projects, making us a reference partner in several business areas, including:",
    "anos": "Years",
    "areas-negocios-contador": "Business Areas",
    "trabalhadores": "workers",
    "clientes": "Clients",
    // Business Areas
    "empresas": "Business Areas",
    "descricao-areas1": "Unione Group's strength lies in its ability to operate in an integrated manner, articulating different companies in strategic sectors of the economy.",
    "descricao-areas2": "This synergy allows us to execute projects with agility, optimize resources and expand the impact of each investment — from planning to delivery.",
    "descricao-areas3": "With a connected structure that goes from production to service, from technical training to energy and distribution, we offer complete solutions for real challenges, creating sustainable value in the markets where we operate.",
    "descricao-areas4": "Discover our integrated structure and see how we turn diverse skills into concrete results.",
    // Investors
    "investidores-titulo": "Investors",
    "descricao-investidores": "We act as strategic facilitators for companies and investors wishing to establish themselves in Angola, connecting local opportunities to global capital and providing structured support for sustainable, long-term investments.",
    "como-apoiamos": "How do we support investors?",
    "seguranca-juridica": "Legal security and installation support",
    "oportunidade-valorizacao": "Valuation opportunity",
    "localizacao-estrategica": "Strategic location and connectivity",
    "infraestrutura-pronta": "Ready-to-operate infrastructure",
    "beneficio1": "Development of personalized architecture and engineering projects",
    "beneficio2": "Legal security with registered lots and automatic property transfer",
    "beneficio3": "Business incubation in the first years of activity",
    "beneficio4": "Professional Technician Training",
    "beneficio5": "Support in the installation and operation of production units with agility and efficiency",
    // POLIS
    "polis-titulo": "POLIS - Integrated Development Hub and Sustainability",
    "descricao-polis1": "POLIS is a benchmark project in the Angolan market, developed and managed by Unione Group and designed as an Integrated and Sustainable Development Hub, with ready infrastructure, organized management and a vocation to receive industries, service companies and high value-added housing projects.",
    "descricao-polis2": "More than a real estate development, POLIS offers a structured, strategic and legally secure environment for business installation, logistics expansion and housing development with quality of life.",
    "area-bruta": "Gross Area",
    "area-construida": "Built Area",
    "lotes": "Lots",
    "industriais-comerciais-residenciais": "Industrial, Commercial and Residential",
    "centros-desenvolvimento": "Development Centers - CT",
    "cd1": "CD 1 | Industrial",
    "cd2": "CD 2 | Commerce and Services",
    "cd3": "CD 3 | Health and Aesthetics",
    "cd4": "CD 4 | Education and Training",
    "cd5": "CD 5 | Hospitality and Tourism",
    "cd6": "CD 6 | Culture, Sports and Leisure",
    "cd7": "CD 7 | Residential",
    "cd8": "CD 8 | Community Support Services",
    "beneficios-investidores": "Benefits for Investors",
    "beneficio-logistica": "Reduction of logistics costs and response time",
    "beneficio-valorizacao": "Continuous appreciation potential with an innovative and growing project",
    "beneficio-mercados": "Simultaneous access to local, national and cross-border markets",
    "beneficio-competitiva": "Competitive advantage in regional marketing, especially in the agri-food chain",
    "beneficio-importacao": "Ease of importing/exporting inputs and finished products",
    "saber-mais-lotes": "learn more about Lots",
    "polis-destino-estrategico": "What makes POLIS a strategic destination for investors:",
    "polis-lotes-infra": "Fully Infrastructured Lots",
    "polis-suporte-desenvolvimento": "Business Development Support and Monitoring",
    "polis-promocao-escoamento": "Promotion and Flow of Products and Services",
    "polis-planeamento-sustentavel": "Sustainable planning",
    // Strategic Location
    "localizacao-estrategica-titulo": "Strategic Location",
    "descricao-localizacao1": "With a consolidated presence in a key region of Angola, Unione Group benefits from a geographical location that boosts its logistics, operational and commercial capacity. Proximity to relevant markets, logistics corridors and strategic borders ensures greater operational efficiency and lower distribution costs.",
    "descricao-localizacao2": "POLIS – Integrated and Sustainable Development Hub, located in the Huíla region, in Humpata, is the logistical and territorial center of our operations, with direct access to:",
    "descricao-localizacao3": "This strategic position reinforces our competitiveness in national and international markets, reducing logistics times, increasing distribution coverage and enabling large-scale operations for different sectors.",
    // Contact
    "fale-conosco": "Talk to us",
    "seu-nome": "Your Name",
    "seu-email": "Your Email",
    "particular": "Individual",
    "empresa": "Company",
    "mensagem": "Message",
    "enviar": "Send",
    // Footer
    "direitos-reservados": "All rights reserved",
    // Benefícios dinâmicos do POLIS - Aba 1
    "polis1_beneficio1": "Sanitation networks.",
    "polis1_beneficio2": "Electric Power.",
    "polis1_beneficio3": "Water Supply.",
    "polis1_beneficio4": "Waste collection.",
    "polis1_beneficio5": "Internet.",
    "polis1_beneficio6": "Fiber Optics.",
    "polis1_beneficio7": "Internal Roads.",
    "polis1_beneficio8": "24h Private Security.",
    // Aba 2
    "polis2_beneficio1": "Development of personalized architecture and engineering projects.",
    "polis2_beneficio2": "Legal security with registered lots and automatic property transfer.",
    "polis2_beneficio3": "Business incubation in the first years of activity.",
    "polis2_beneficio4": "Professional Technician Training.",
    "polis2_beneficio5": "Support in the installation and operation of production units with agility and efficiency.",
    // Aba 3
    "polis3_beneficio1": "Permanent Exhibition Center for the promotion and marketing of products and services of installed companies.",
    "polis3_beneficio2": "Logistics Distribution Center.",
    // Aba 4
    "polis4_beneficio1": "Green spaces and internal mobility solutions.",
    "polis4_beneficio2": "Quality of life in the work environment.",
    "polis4_beneficio3": "Continuous appreciation with an innovative and growing project.",
    // Swiper card titles
    "saude": "Health",
    "hotelaria": "Hospitality",
    "energia": "Energy",
    "ensino": "Education",
    "agro-industria": "Agro-industry",
    "mecanica-industrial": "Industrial Mechanics",
    "investimento-consultoria": "Investment and Consulting",
    "metalurgia": "Metallurgy and Metalworking",
    "tecnologia": "Telecommunications",
    "marcenaria-carpintaria": "Carpentry and Joinery",
    "construcao-civil": "Civil Construction",
    "consultoria-juridica": "Legal Consulting"
  },
  fr: {
    // Menu et navigation
    "grupo-unione": "groupe unione",
    "areas-negocios": "Secteurs d'activité",
    "investidores": "Investisseurs",
    "polis": "polis",
    "contatos": "Contacts",
    "contacte-nos": "Contactez-nous",
    "siga-nos": "Suivez-nous",
    // Hero/Groupe
    "o-grupo-unione": "Le Groupe Unione",
    "excelencia-angolana": "Excellence angolaise dans chaque investissement.",
    "descricao-grupo": "Le Groupe Unione est un groupe d'affaires et d'investissement angolais, opérant stratégiquement dans des secteurs clés de l'économie.",
    "descricao-grupo2": "Notre diversification et notre capacité opérationnelle sont démontrées par des projets à fort impact, faisant de nous un partenaire de référence dans plusieurs domaines d'activité, notamment :",
    "anos": "Ans",
    "areas-negocios-contador": "Secteurs d'activité",
    "trabalhadores": "travailleurs",
    "clientes": "Clients",
    // Secteurs d'activité
    "empresas": "Secteurs d'activité",
    "descricao-areas1": "La force du Groupe Unione réside dans sa capacité à opérer de manière intégrée, en articulant différentes entreprises dans des secteurs stratégiques de l'économie.",
    "descricao-areas2": "Cette synergie permet d'exécuter des projets avec agilité, d'optimiser les ressources et d'amplifier l'impact de chaque investissement — de la planification à la livraison.",
    "descricao-areas3": "Avec une structure connectée allant de la production au service, de la formation technique à l'énergie et à la distribution, nous offrons des solutions complètes pour des défis réels, créant une valeur durable sur les marchés où nous opérons.",
    "descricao-areas4": "Découvrez notre structure intégrée et voyez comment nous transformons des compétences diverses en résultats concrets.",
    // Investisseurs
    "investidores-titulo": "Investisseurs",
    "descricao-investidores": "Nous agissons en tant que facilitateurs stratégiques pour les entreprises et les investisseurs souhaitant s'implanter en Angola, en reliant les opportunités locales aux capitaux mondiaux et en fournissant un soutien structuré pour des investissements durables et à long terme.",
    "como-apoiamos": "Comment soutenons-nous les investisseurs ?",
    "seguranca-juridica": "Sécurité juridique et soutien à l'installation",
    "oportunidade-valorizacao": "Opportunité de valorisation",
    "localizacao-estrategica": "Emplacement et connectivité stratégiques",
    "infraestrutura-pronta": "Infrastructure prête à l'emploi",
    "beneficio1": "Élaboration de projets d'architecture et d'ingénierie personnalisés",
    "beneficio2": "Sécurité juridique avec des lots enregistrés et transfert automatique de propriété",
    "beneficio3": "Incubation d'entreprises dans les premières années d'activité",
    "beneficio4": "Formation de techniciens professionnels",
    "beneficio5": "Soutien à l'installation et à l'exploitation d'unités de production avec agilité et efficacité",
    // POLIS
    "polis-titulo": "POLIS - Pôle de Développement Intégré et Durabilité",
    "descricao-polis1": "POLIS est un projet de référence sur le marché angolais, développé et géré par le Groupe Unione et conçu comme un Pôle de Développement Intégré et Durable, avec une infrastructure prête, une gestion organisée et une vocation à accueillir des industries, des entreprises de services et des projets résidentiels à forte valeur ajoutée.",
    "descricao-polis2": "Plus qu'un projet immobilier, POLIS offre un environnement structuré, stratégique et juridiquement sûr pour l'installation d'entreprises, l'expansion logistique et le développement résidentiel avec qualité de vie.",
    "area-bruta": "Superficie brute",
    "area-construida": "Superficie construite",
    "lotes": "Lots",
    "industriais-comerciais-residenciais": "Industriels, Commerciaux et Résidentiels",
    "centros-desenvolvimento": "Centres de Développement - CT",
    "cd1": "CD 1 | Industriel",
    "cd2": "CD 2 | Commerce et Services",
    "cd3": "CD 3 | Santé et Esthétique",
    "cd4": "CD 4 | Éducation et Formation",
    "cd5": "CD 5 | Hôtellerie et Tourisme",
    "cd6": "CD 6 | Culture, Sport et Loisirs",
    "cd7": "CD 7 | Résidentiel",
    "cd8": "CD 8 | Services de soutien à la communauté",
    "beneficios-investidores": "Avantages pour les investisseurs",
    "beneficio-logistica": "Réduction des coûts logistiques et du temps de réponse",
    "beneficio-valorizacao": "Potentiel d'appréciation continue avec un projet innovant et en croissance",
    "beneficio-mercados": "Accès simultané aux marchés locaux, nationaux et transfrontaliers",
    "beneficio-competitiva": "Avantage concurrentiel dans la commercialisation régionale, notamment dans la chaîne agroalimentaire",
    "beneficio-importacao": "Facilité d'importation/exportation d'intrants et de produits finis",
    "saber-mais-lotes": "en savoir plus sur les Lots",
    "polis-destino-estrategico": "Qu'est-ce qui fait du POLIS une destination stratégique pour les investisseurs :",
    "polis-lotes-infra": "Lots entièrement équipés d'infrastructures",
    "polis-suporte-desenvolvimento": "Accompagnement et soutien au développement des entreprises",
    "polis-promocao-escoamento": "Promotion et écoulement des produits et services",
    "polis-planeamento-sustentavel": "Planification durable",
    // Emplacement stratégique
    "localizacao-estrategica-titulo": "Emplacement stratégique",
    "descricao-localizacao1": "Avec une présence consolidée dans une région clé de l'Angola, le Groupe Unione bénéficie d'un emplacement géographique qui renforce sa capacité logistique, opérationnelle et commerciale. La proximité des marchés pertinents, des corridors logistiques et des frontières stratégiques garantit une plus grande efficacité opérationnelle et des coûts de distribution réduits.",
    "descricao-localizacao2": "POLIS – Pôle de Développement Intégré et Durable, situé dans la région de Huíla, à Humpata, constitue le centre logistique et territorial de nos opérations, avec un accès direct à :",
    "descricao-localizacao3": "Cette position stratégique renforce notre compétitivité sur les marchés nationaux et internationaux, réduisant les temps logistiques, augmentant la couverture de distribution et permettant des opérations à grande échelle pour différents secteurs.",
    // Contact
    "fale-conosco": "Parlez-nous",
    "seu-nome": "Votre nom",
    "seu-email": "Votre e-mail",
    "particular": "Particulier",
    "empresa": "Entreprise",
    "mensagem": "Message",
    "enviar": "Envoyer",
    // Footer
    "direitos-reservados": "Tous droits réservés",
    // Avantages dynamiques POLIS - Onglet 1
    "polis1_beneficio1": "Réseaux d'assainissement.",
    "polis1_beneficio2": "Énergie électrique.",
    "polis1_beneficio3": "Approvisionnement en eau.",
    "polis1_beneficio4": "Collecte des déchets.",
    "polis1_beneficio5": "Internet.",
    "polis1_beneficio6": "Fibre optique.",
    "polis1_beneficio7": "Voiries internes.",
    "polis1_beneficio8": "Sécurité privée 24h/24.",
    // Onglet 2
    "polis2_beneficio1": "Élaboration de projets d'architecture et d'ingénierie personnalisés.",
    "polis2_beneficio2": "Sécurité juridique avec des lots enregistrés et transfert automatique de propriété.",
    "polis2_beneficio3": "Incubation d'entreprises dans les premières années d'activité.",
    "polis2_beneficio4": "Formation de techniciens professionnels.",
    "polis2_beneficio5": "Soutien à l'installation et à l'exploitation d'unités de production avec agilité et efficacité.",
    // Onglet 3
    "polis3_beneficio1": "Centre d'exposition permanent pour la promotion et la commercialisation des produits et services des entreprises installées.",
    "polis3_beneficio2": "Centre logistique de distribution.",
    // Onglet 4
    "polis4_beneficio1": "Espaces verts et solutions de mobilité interne.",
    "polis4_beneficio2": "Qualité de vie dans l'environnement de travail.",
    "polis4_beneficio3": "Valorisation continue avec un projet innovant et en croissance.",
    // Titres des cartes swiper
    "saude": "Santé",
    "hotelaria": "Hôtellerie",
    "energia": "Énergie",
    "ensino": "Enseignement",
    "agro-industria": "Agro-industrie",
    "mecanica-industrial": "Mécanique Industrielle",
    "investimento-consultoria": "Investissement et Conseil",
    "metalurgia": "Métallurgie et Métallomécanique",
    "tecnologia": "Télécommunications",
    "marcenaria-carpintaria": "Menuiserie et Charpenterie",
    "construcao-civil": "Construction Civile",
    "consultoria-juridica": "Conseil juridique"
  }
}; 